name: Ladesäulen Reservierung

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: ▶️ Run script
        run: python main.py

      - name: 📸 Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            1_after_login.png
            2_after_morgen.png
            3_after_dropdown.png
            4_after_reservieren.png
            log.txt
